### ISSUE TITLE
Cant run the server

### ISSUE THREAD

**Issue by NolikTop** [Irmine/GoMine#15]
#### Description
I installed GoMine, Go 1.9.2, and then ran start.cmd and an error occurred

#### Information
* GoMine Version:
0.0.1
* GoMine Commit/Release:
209142bbfde7ffb2ee479aa85fbfe6fa467bee91
* Operating System:
Windows
* Game Variant:
W10

#### Plugins
Nothing

#### Crash/Error
```go
# gomine/worlds 
src\gomine\worlds\Level.go:142:9: constant 429496729500 overflows int 
src\gomine\worlds\Level.go:142:54: constant 4294967295 overflows int 
src\gomine\worlds\Level.go:149:35: constant 4294967295 overflows int
```

**Comment by Sandertv** [comment]
Do you use a 32 bit machine or a 64 bit?

**Comment by NolikTop** [comment]
I use 64
![image](https://user-images.githubusercontent.com/17119018/35471757-4bfe299c-037b-11e8-8fdc-95655fde90e2.png)

**Comment by Sandertv** [comment]
Alright, looking into it.
