### ISSUE TITLE
It's impossible to set up developing environment with instructions given in readme.

### ISSUE THREAD

**Issue by Snake1999** [Irmine/GoMine#16]
When I began in my console, it says:
```bash
192:~ lmlstarqaq$ ls
Desktop		GolandProjects	Movies		Public
Documents	IdeaProjects	Music		easecation
Downloads	Library		Pictures
192:~ lmlstarqaq$ mkdir gomine
192:~ lmlstarqaq$ cd gomine
192:gomine lmlstarqaq$ go get github.com/Irmine/GoMine
package github.com/Irmine/GoMine: no Go files in /Users/mac/gopath/src/github.com/Irmine/GoMine
```
`no Go files`, everything but a sign of success. :/ What should I do?
I am equipped with macOS 10.13.2, command-line git installed, with an ide called 'jetbrains goland'.

**Comment by Sandertv** [comment]
You could also try cloning the repository recursively with git.

**Comment by Snake1999** [comment]
maybe i'm not good at english, though :/
```
To clone the repository, use either: go get github.com/Irmine/GoMine, or, if you have Git installed: git clone --recursive https://github.com/Irmine/GoMine
```

**Comment by Sandertv** [comment]
The `go get` command usually gives that error but does clone it correctly. Try looking for an `src` repo somewhere. You said you had git. You can use this to clone the repository too:
`git clone --recursive https://github.com/Irmine/GoMine`

**Comment by Snake1999** [comment]
<img width="545" alt="qq20180127-200659 2x" src="https://user-images.githubusercontent.com/7609294/35471799-a74ea0c0-039d-11e8-8898-4117bb3f8d96.png">

Yes i've done all the commands.

**Comment by Sandertv** [comment]
Okay. So what's the problem?

**Comment by Snake1999** [comment]
I've found the problem. 

The github project GoMine is UPPER-CASED, while inside the code gomine is lower-cased, which caused case-sensitive macOS impossible to automatically iterate to update the files. I'll do in my computer to rename all the files lower-cased, but I do not guarantee no other developers who contribute to gomine avoid suffering this problem.

Sorry to have bothered you.

**Comment by Sandertv** [comment]
Not sure how exactly this would impact it. I personally dislike the general way the Go workspace works, which is why I haven't touched it too much. I'm going to close it for now. If you find particular ways to make the process of setting it up easier, please do feel free to make a PR.
