### ISSUE TITLE
#offtop

### ISSUE THREAD

**Issue by c0caina** [Irmine/GoMine#27]
I'm translating Google Translate
Why did the project die?
Are there any very deep insoluble problems?
Or, perhaps, the realization that this development does not make sense?
What problems have you encountered? In particular, from the technical side.
I apologize in advance. Perhaps the answers to my questions are obvious, and the answers are on the surface, but still I would like to ask these questions.
Theoretically, can this project contain a commercial server if development is completed?

**Comment by Sandertv** [comment]
Hello,

We decided not to continue the project because it was designed very poorly and didn't quite meet our expectations. I'm currently working on a similar project, but have yet to decide whether to and when to open source it.

**Comment by c0caina** [comment]
Thanks for the answer.  I'm sorry that the project failed.  I hope the problem was not in the Golang itself?

**Comment by Sandertv** [comment]
Nah, absolutely not. When we wrote this we were just very inexperienced with it.
