### ISSUE TITLE
dear sandertv, potensial partnership have came to answer you quest for riches

### ISSUE THREAD

**Issue by trantechQuinchio** [Irmine/GoMine#6]
we become rich together, and beat dktapps by selling GoMine !

open source, free sofware, for the people - non profits !

to start , we needs make goals. (like how chicken make egg and vice versa)

i think we may best approach potensials with:
- rename gomine to genisyspro2
- advertise on pmmp project
- run dktapps buisness down
- be claimed crown !!!!!

please consider make me admin, soon we get very rich if you let me help

**Comment by TheDeibo** [comment]
Hello. 
Shoghi approves of dktapps. It's still Shoghi's business. So, calm down boiiii!

Besides, you got it alllll wrong. 

But #BETTYFORPRESIDENT!

**Comment by eDroiid** [comment]
kys

**Comment by Thunder33345** [comment]
we become rich together by killing spammers

to start , we needs make goals. (like how chicken make egg and vice versa)

i think we may best approach potentials with:

setting interaction limit

ban people who send spams

get a bot to ban everyone who sends spam

make people pay to be unbanned

please consider make me admin, soon we get very rich if you let me help

**Comment by eDroiid** [comment]
wE bECOmE rICh ToGEtHer, anD BEat dKTapPS by seLlInG goMINe !

opeN SOurCE, Free sOFwarE, foR tHe PeoPLE - nOn PRoFits !

to stArT , wE NeEdS make GoAlS. (LIkE hOW cHICkeN mAke egG AND VIcE VeRSa)

I ThiNk we MAy besT appRoacH pOtENsiAls With:

RENAmE GoMiNE tO genIsySPro2
adVerTISe oN PMMp PROjECT
RUN Dktapps buIsNEsS DoWN
bE clAImED croWN !!!!!
pleasE consiDer mAkE Me admiN, sOon We gEt VeRY riCH iF yoU let mE helP

![image](https://user-images.githubusercontent.com/19215259/32996544-d7af2c4e-cd38-11e7-9f62-7eca10ce45ec.png)
