### ISSUE TITLE
FUCK YOU FOR RUDE BEHAVIOUR !

### ISSUE THREAD

**Issue by betty4352** [Irmine/GoMine#7]
YOU RUDE @Sandertv IM TRY TO HELP GOMINE YOU DENY IT !

WE COULD HAVE BEEN VERY RICH SELL GOMINE BUT U MAKE DKTAPPS GET ALL PROFITS ! NOT FAIR ! ECONOMIC FREEDOM MUST COME FROM GOMINE ! I WILL MAKE GOMINE PRO TO SELL VERY SOON, AND YOU WILL REGRET THIS DAY  UNDER ACTION !

**Comment by eDroiid** [comment]
YOU rUDE @sandertv im tRy TO HeLp gomINe yoU DEny it !

WE CoULD HAvE BeEn VErY RiCh sELL GOmInE but u MakE dkTaPPS gEt ALL ProfitS ! not FAIR ! EcOnoMic FrEEdom mUsT CoME FRom gOminE ! I wiLl MaKE GOMIne Pro TO sell Very sooN, ANd YoU wIlL REGrET ThIS dAY Under acTIoN !

![image](https://user-images.githubusercontent.com/19215259/33103905-0fddde2e-ceda-11e7-8ade-3920f7968c67.png)
